OnlineCoursePlatform.Web/Areas/UserPanel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCoursePlatform.Core.Services.Interfaces;
using OnlineCoursePlatform.Core.Convertors;
using OnlineCoursePlatform.DataLayer.Entities.User;
using OnlineCoursePlatform.Core.Senders;
using OnlineCoursePlatform.Core.DTOs.User;

namespace OnlineCoursePlatform.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IUserService _userService;
        private readonly IViewRenderService _viewRenderService;
        public HomeController(IUserService userService, IViewRenderService viewRenderService)
        {
            _userService= userService;
            _viewRenderService= viewRenderService;
        }

        public IActionResult Index() => View(_userService.GetUserInformation(User.Identity.Name));

        [Route("UserPanel/EditProfile")]
        public IActionResult EditProfile() => View(_userService.GetDataForUserProfileEdit(User.Identity.Name));

        [Route("UserPanel/EditProfile")]
        [HttpPost]
        public IActionResult EditProfile(EditProfileViewModel editProfileViewModel)
        {
            if (!ModelState.IsValid)
                return View(editProfileViewModel);

            User user = _userService.GetUserByUserName(User.Identity.Name);
            bool isEmailChanged = false;

            if((user.Email == editProfileViewModel.Email && user.UserName == editProfileViewModel.UserName) && editProfileViewModel.UserAvatar == null)
            {
                ModelState.AddModelError("Email", "لطفا اطلاعات وارد شده را تغییر دهید");
                return View(editProfileViewModel);
            }

            if (user.UserName != editProfileViewModel.UserName)
            {
                if (_userService.IsUserNameExist(editProfileViewModel.UserName))
                {
                    ModelState.AddModelError("UserName", "نام کاریری تکراری است ");
                    return View(editProfileViewModel);
                }
            }

            if (user.Email != editProfileViewModel.Email)
            {
                if (_userService.IsEmailExist(FixedText.FixedEmail(editProfileViewModel.Email)))
                {
                    ModelState.AddModelError("Email", "ایمیل تکراری است");
                    return View(editProfileViewModel);
                }
                _userService.DeActiveAccount(User.Identity.Name);
                isEmailChanged = true;
                string emailBody = _viewRenderService.RenderToStringAsync("_EmailChanged", user);
                SendEmail.Send(editProfileViewModel.Email, "فعالسازی حساب کاربری", emailBody);
            }

            _userService.EditProfile(User.Identity.Name, editProfileViewModel);

            // Logout User
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login","Account", new {editProfile = true, isEmailChanged});
        }

        [Route("UserPanel/ChangePassword")]
        public IActionResult ChangePassword() => View();

        [Route("UserPanel/ChangePassword")]
        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            string userName = User.Identity.Name;
            if (!ModelState.IsValid)
                return View(changePasswordViewModel);

            if(!_userService.CompareOldPassword(userName, changePasswordViewModel.OldPassword))
            {
                ModelState.AddModelError("OldPassword", "کلمه عبور فعلی صحیح نمیباشد");
                return View(changePasswordViewModel);
            }

            _userService.ChangeUserPassword(userName, changePasswordViewModel.Password);
            ViewBag.IsSuccess = true;

            return View();
        }
    }
}

OnlineCoursePlatform.Web/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using OnlineCoursePlatform.Core.Services.Interfaces;
using OnlineCoursePlatform.DataLayer.Entities.Course;
using SharpCompress.Archives;

namespace OnlineCoursePlatform.Web.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        public CourseController(ICourseService courseService, IOrderService orderService, IUserService userService)
        {
            _courseService = courseService;
            _orderService = orderService;
            _userService = userService;
        }

        public IActionResult Index(int pageId = 1, string filter = null,
            string getType = "all", string orederByType = "date", int startPrice = 0,
            int endPrice = 0, List<int> selectedGroups = null)
        {
            ViewBag.filter = filter;
            ViewBag.getType = getType;
            ViewBag.selectedGroups = selectedGroups;
            ViewBag.pageId = pageId;

            ViewBag.Groups = _courseService.GetAllGroups();

            return View(_courseService.GetCourses(pageId, filter, getType, orederByType, startPrice, 
                endPrice, selectedGroups, 9));
        }

        [Route("/ShowCourse/{courseId}")]
        public IActionResult ShowCourse(int courseId, int episodeId = 0)
        {
            Course course = _courseService.GetCourseDetailsById(courseId);

            if (course == null)
                return NotFound();

            if (episodeId != 0 && User.Identity.IsAuthenticated)
                if (course.CourseEpisodes.All(e => e.EpisodeId != episodeId)) return NotFound();

            if (episodeId != 0 && !course.CourseEpisodes.Single(e => e.EpisodeId == episodeId).IsFree)
                if (!_orderService.IsUserInCourse(User.Identity.Name, courseId)) return NotFound();

            CourseEpisode? episode = null;
            string filePath = "";
            string checkFilePath = "";

            if (episodeId != 0) episode = course.CourseEpisodes.First(e => e.EpisodeId == episodeId);
            ViewBag.Episode = episode;


            if (episodeId != 0 && episode.IsFree)
            {
                filePath = "/freeCourseOnline/" + episode.EpisodeFileName.Replace(".rar", ".mp4");
                checkFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/freeCourseOnline",
                    episode.EpisodeFileName.Replace(".rar", ".mp4"));
            }
           
            else if(episodeId != 0)
            {
                filePath = "/courseOnline/" + episode.EpisodeFileName.Replace(".rar", ".mp4");
                checkFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/courseOnline",
                    episode.EpisodeFileName.Replace(".rar", ".mp4"));
            }
            

            if(episodeId != 0 && !System.IO.File.Exists(checkFilePath)) 
            {
                string targetPath = Directory.GetCurrentDirectory();

                if(episode.IsFree && episodeId != 0) targetPath = Path.Combine(targetPath, "wwwroot/freeCourseOnline");

                else if(episodeId != 0) targetPath = Path.Combine(targetPath, "wwwroot/courseOnline");

                string rarPath = Path.Combine(Directory.GetCurrentDirectory(),
                    "wwwroot/courseFiles", episode.EpisodeFileName);

                IArchive archive = ArchiveFactory.Open(rarPath);
                var entries = archive.Entries.OrderBy(x => x.Key.Length);
                foreach(var entry in entries)
                {
                    if (Path.GetExtension(entry.Key) == ".mp4")
                        entry.WriteTo(System.IO.File.Create(Path.Combine(targetPath
                            , episode.EpisodeFileName.Replace(".rar", ".mp4"))));
                }
            }
            ViewBag.FilePath = filePath;

            return View(course);
        }

        [Authorize]
        public IActionResult BuyCourse(int courseId)
        {
            int orderId = _orderService.InsertOrder(User.Identity.Name, courseId);
            return Redirect("/UserPanel/Order/ShowOrder?orderId=" + orderId);
        }

        [Route("DownloadFile/{episodeId}")]
        public IActionResult DownloadFile(int episodeId)
        {
            CourseEpisode episode = _courseService.GetEpisodeById(episodeId);
            string fileName = episode.EpisodeFileName;
            string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/courseFiles", fileName);
            if(episode.IsFree)
            {
                byte[] file = System.IO.File.ReadAllBytes(filePath);
                return File(file, "application/force-download", fileName);
            }

            if (User.Identity.IsAuthenticated)
            {
                if(_orderService.IsUserInCourse(User.Identity.Name, episode.CourseId) 
                    || episode.Course.TeacherId == _userService.GetUserIdByUserName(User.Identity.Name))
                {
                    byte[] file = System.IO.File.ReadAllBytes(filePath);
                    return File(file, "application/force-download", fileName);
                }
            }
            return Forbid();
        }

        [HttpPost]
        public IActionResult CreateComment(CourseComment comment)
        {
            if(comment.Comment != null)
            {
                comment.CreateDate = DateTime.Now;
                comment.UserId = _userService.GetUserIdByUserName(User.Identity.Name);
                _courseService.AddComment(comment);
            }
            return View("ShowComment", _courseService.GetComments(comment.CourseId));
        }

        public IActionResult ShowComment(int id, int pageId = 1)
        {
            return View(_courseService.GetComments(id, pageId));
        }

        [Authorize]
        public IActionResult CourseVote(int courseId)
        {
            if (!_courseService.IsCourseFree(courseId)
                && !_orderService.IsUserInCourse(User.Identity.Name, courseId)) ViewBag.AccessDenied = true;
            return PartialView(_courseService.GetCourseVotes(courseId));
        }

        [Authorize]
        public IActionResult AddVote(int id, bool vote)
        {
            _courseService.AddVote(_userService.GetUserIdByUserName(User.Identity.Name), id, vote);
            return PartialView("CourseVote", _courseService.GetCourseVotes(id));
        }
    }
}

OnlineCoursePlatform.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineCoursePlatform.Core.Generators;
using OnlineCoursePlatform.Core.Services.Interfaces;
using OnlineCoursePlatform.DataLayer.Entities.Wallet;
using ZarinpalSandbox;

namespace OnlineCoursePlatform.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICourseService _courseService;
        public HomeController(IUserService userService, ICourseService courseService) 
        {
            _userService = userService;
            _courseService = courseService;
        }
        public IActionResult Index() 
        {
            ViewBag.PopularCourses = _courseService.GetPopularCourses();
            return View();
        } 

        [Route("OnlinePayment/{id}")]
        public IActionResult OnlinePayment(int id)
        {
            if (HttpContext.Request.Query["Status"] != "" &&
                HttpContext.Request.Query["Status"].ToString().ToLower() == "ok" &&
                HttpContext.Request.Query["Authority"] != "")
            {
                string authority = HttpContext.Request.Query["Authority"];
                Wallet wallet = _userService.GetWalletByWalletId(id);
                Payment payment = new Payment(wallet.Amount);
                var res = payment.Verification(authority).Result;
                if(res.Status == 100)
                {
                    ViewBag.Code = res.RefId;
                    ViewBag.IsSuccess = true;
                    wallet.IsPay = true;
                    _userService.Save();
                }
            }

            return View();
        }

        public IActionResult GetSubGroups(int id)
        {
            List<SelectListItem> subGroups = new List<SelectListItem>()
            {
                new SelectListItem() {Text = "انتخاب کنید", Value = ""}
            };
            subGroups.AddRange(_courseService.GetSubGroupForManageCourse(id));
            return Json(new SelectList(subGroups, "Value", "Text"));
        }

        [HttpPost]
        [Route("file-upload")]
        public IActionResult UploadImage(IFormFile upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            if (upload.Length <= 0) return null;

            var fileName = NameGenerator.GenerateUniqCode() + Path.GetExtension(upload.FileName).ToLower();

            var path = Path.Combine(
                Directory.GetCurrentDirectory(), "wwwroot/MyImages",
                fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                upload.CopyTo(stream);
            }

            var url = $"{"/MyImages/"}{fileName}";

            return Json(new { uploaded = true, url });
        }

        [Route("Contact")]
        public IActionResult Contact() => View();

        [Route("About")]
        public IActionResult About() => View();

        public IActionResult Error404() => View();
    }
}

OnlineCoursePlatform.Web/ViewComponents/LatestCoursesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineCoursePlatform.Core.Services.Interfaces;
using System.Xml.Serialization;

namespace OnlineCoursePlatform.Web.ViewComponents
{
    public class LatestCoursesViewComponent : ViewComponent
    {
        private readonly ICourseService _courseService;
        public LatestCoursesViewComponent(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("LatestCourses", _courseService.GetCourses().Item1));
        }
    }
}

OnlineCoursePlatform.Web/ViewComponents/PopularCoursesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineCoursePlatform.Core.Services.Interfaces;

namespace OnlineCoursePlatform.Web.ViewComponents
{
    public class PopularCoursesViewComponent : ViewComponent
    {
        private readonly ICourseService _courseService;
        public PopularCoursesViewComponent(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("PopularCourses", _courseService.GetPopularCourses()));
        }
    }
}

OnlineCoursePlatform.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "درباره";
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">پلتفرم دوره های آنلاین</a></li>
            <li class="breadcrumb-item active" aria-current="page"> درباره سایت </li>
        </ul>
    </nav>
</div>

<main id="home-page">
    <div class="container">
        <section class="terms-items">
            <header>
                <h2> درباره سایت </h2>
            </header>
            <p>
                     این سایت یک پلتفرم برای دوره های آنلاین است که کاربران در آن می توانند دوره مختلف را به سادگی پیدا و مشاهده کنند زیرا که قسمت فیلتر و سرچ سایت به صورت کاملی پیاده سازی شده است.
                     از ویژگی های آن میتوان استفاده از معماری MVC و استفاده از Razor Page ها برای پنل ادمین نام برد.       
                     و علاوه بر معماری تمیز سطوح دسترسی نقش های مختلف نیز در این سایت کنترل شده است.
                     در این سایت کاربر پس از افزودن دوره ها به سبد خرید خود می تواند از کدهای تخفیف استفاده کند و بعد از اعمال تخفیف از طریق شارژ کیف پول که با استفاده از درگاه تست زرین پال پیاده سازی شده است، کیف پول خود را شارژ و دوره ها را خریداری کندو پس از آن فاکتور های خود را در پنل کاربری مشاهده کند.
                   مدرس دوره نیز می تواند با مراجعه به پنل مدرس دوره های خود را کنترل و به روز رسانی کند.
            </p>
        </section>
    </div>
</main>

OnlineCoursePlatform.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "ارتباط با ما";
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">پلتفرم دوره های آنلاین</a></li>
            <li class="breadcrumb-item active" aria-current="page">تماس با ما</li>
        </ul>
    </nav>
</div>

<main class="client-page">
    <div class="container-content">
        <header>
            <h2>راه های ارتباطی</h2>
        </header>

        <div class="form-layer justify-content-center">
            <ul>
                <li>
                    <b>
                        تلفن : 09392906609
                    </b>
                </li>
                <br />
                <li>
                    <b>
                         ایمیل : ParsaDdshi@gmail.com
                    </b>
                </li>
                <br />
                <li>
                    <b>
                        آیدی تلگرام : Parsa_Ddsh
                    </b>
                </li>
            </ul>
        </div>
    </div>
</main>

OnlineCoursePlatform.Web/Views/Home/Error404.cshtml
@{
    ViewData["Title"] = "صفحه مورد نظر یافت نشد";
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">پلتفرم دوره های آنلاین</a></li>
            <li class="breadcrumb-item active" aria-current="page"> خطای 404</li>
        </ul>
    </nav>
</div>
<div class="container">
    <div class="text-center">
        <a class="btn btn-info text-center" asp-controller="Home" asp-action="Index">بازگشت به صفحه اصلی</a>
    </div>
    <br />
    <img src="/errorImg/error.jpg" />
</div>

OnlineCoursePlatform.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "خانه";
}

@section SearchBox
{
  <header>
    <h1> با اساتید مجرب و کارآزموده  </h1>
    <h2> آموزش ببینید ، تجربه کسب کنید و بازار کار شوید </h2>
    <h3> با کمترین هزینه خودت یاد بگیر </h3>
  </header>
  <div class="search-form">
    <form asp-controller="Course" asp-action="Index" method="get">
        <input type="text" name="filter" id="term" placeholder="چی دوست داری یاد بگیری ؟">
        <button><i class="zmdi zmdi-search"></i></button>
    </form>
  </div>
}

<main id="home-page">
    <div class="container">
        <section class="terms-items">
            <header>
                <h2> آخرین دوره ها </h2>
            </header>
            <div class="row">
                <cache expires-after="@TimeSpan.FromMinutes(5)">
                    @await Component.InvokeAsync("LatestCourses")
                </cache>
            </div>
        </section>

        <hr>

        <section class="terms-items">
            <header>
                <h2>پرفروش ترین دوره ها</h2>
            </header>
            <div class="row">
                <cache expires-after="@TimeSpan.FromHours(1)">
                    @await Component.InvokeAsync("PopularCourses")
                </cache>
            </div>
        </section>
     </div>
</main>

@section Scripts
{
    <script>
        $(document).ready(function(){
            $("#term").autocomplete({
                source: 'api/CourseApi/search?term=' + $("#term").val
            })
        });
    </script>
}

OnlineCoursePlatform.Web/Views/Home/OnlinePayment.cshtml
@{
    ViewData["Title"] = "نتیجه پرداخت";
}

<div class="container">
    <nav aria-label="breadcrumb">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">پلتفرم دوره های آنلاین</a></li>
        <li class="breadcrumb-item active" aria-current="page">نتیجه پرداخت</li>
      </ul>
    </nav>
</div>

<div class="container">
    @if(ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success">
            <h2>پرداخت با موفقیت انجام شد</h2>
            <p>کد پیگیری : @ViewBag.Code</p>
        </div>
    }
    else
    {
        <div class="alert alert-danger">
            <h2>پرداخت با شکست مواجه شد</h2>
        </div>        
    }
</div>