OnlineCoursePlatform.Web/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using OnlineCoursePlatform.Core.Services.Interfaces;
using OnlineCoursePlatform.DataLayer.Entities.Course;
using SharpCompress.Archives;

namespace OnlineCoursePlatform.Web.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        public CourseController(ICourseService courseService, IOrderService orderService, IUserService userService)
        {
            _courseService = courseService;
            _orderService = orderService;
            _userService = userService;
        }

        public IActionResult Index(int pageId = 1, string filter = null,
            string getType = "all", string orederByType = "date", int startPrice = 0,
            int endPrice = 0, List<int> selectedGroups = null)
        {
            ViewBag.filter = filter;
            ViewBag.getType = getType;
            ViewBag.selectedGroups = selectedGroups;
            ViewBag.pageId = pageId;

            ViewBag.Groups = _courseService.GetAllGroups();

            return View(_courseService.GetCourses(pageId, filter, getType, orederByType, startPrice, 
                endPrice, selectedGroups, 9));
        }

        [Route("/ShowCourse/{courseId}")]
        public IActionResult ShowCourse(int courseId, int episodeId = 0)
        {
            Course course = _courseService.GetCourseDetailsById(courseId);

            if (course == null)
                return NotFound();

            if (episodeId != 0 && User.Identity.IsAuthenticated)
                if (course.CourseEpisodes.All(e => e.EpisodeId != episodeId)) return NotFound();

            if (episodeId != 0 && !course.CourseEpisodes.Single(e => e.EpisodeId == episodeId).IsFree)
                if (!_orderService.IsUserInCourse(User.Identity.Name, courseId)) return NotFound();

            CourseEpisode? episode = null;
            string filePath = "";
            string checkFilePath = "";

            if (episodeId != 0) episode = course.CourseEpisodes.First(e => e.EpisodeId == episodeId);
            ViewBag.Episode = episode;


            if (episodeId != 0 && episode.IsFree)
            {
                filePath = "/freeCourseOnline/" + episode.EpisodeFileName.Replace(".rar", ".mp4");
                checkFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/freeCourseOnline",
                    episode.EpisodeFileName.Replace(".rar", ".mp4"));
            }
           
            else if(episodeId != 0)
            {
                filePath = "/courseOnline/" + episode.EpisodeFileName.Replace(".rar", ".mp4");
                checkFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/courseOnline",
                    episode.EpisodeFileName.Replace(".rar", ".mp4"));
            }
            

            if(episodeId != 0 && !System.IO.File.Exists(checkFilePath)) 
            {
                string targetPath = Directory.GetCurrentDirectory();

                if(episode.IsFree && episodeId != 0) targetPath = Path.Combine(targetPath, "wwwroot/freeCourseOnline");

                else if(episodeId != 0) targetPath = Path.Combine(targetPath, "wwwroot/courseOnline");

                string rarPath = Path.Combine(Directory.GetCurrentDirectory(),
                    "wwwroot/courseFiles", episode.EpisodeFileName);

                IArchive archive = ArchiveFactory.Open(rarPath);
                var entries = archive.Entries.OrderBy(x => x.Key.Length);
                foreach(var entry in entries)
                {
                    if (Path.GetExtension(entry.Key) == ".mp4")
                        entry.WriteTo(System.IO.File.Create(Path.Combine(targetPath
                            , episode.EpisodeFileName.Replace(".rar", ".mp4"))));
                }
            }
            ViewBag.FilePath = filePath;

            return View(course);
        }

        [Authorize]
        public IActionResult BuyCourse(int courseId)
        {
            int orderId = _orderService.InsertOrder(User.Identity.Name, courseId);
            return Redirect("/UserPanel/Order/ShowOrder?orderId=" + orderId);
        }

        [Route("DownloadFile/{episodeId}")]
        public IActionResult DownloadFile(int episodeId)
        {
            CourseEpisode episode = _courseService.GetEpisodeById(episodeId);
            string fileName = episode.EpisodeFileName;
            string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/courseFiles", fileName);
            if(episode.IsFree)
            {
                byte[] file = System.IO.File.ReadAllBytes(filePath);
                return File(file, "application/force-download", fileName);
            }

            if (User.Identity.IsAuthenticated)
            {
                if(_orderService.IsUserInCourse(User.Identity.Name, episode.CourseId) 
                    || episode.Course.TeacherId == _userService.GetUserIdByUserName(User.Identity.Name))
                {
                    byte[] file = System.IO.File.ReadAllBytes(filePath);
                    return File(file, "application/force-download", fileName);
                }
            }
            return Forbid();
        }

        [HttpPost]
        public IActionResult CreateComment(CourseComment comment)
        {
            if(comment.Comment != null)
            {
                comment.CreateDate = DateTime.Now;
                comment.UserId = _userService.GetUserIdByUserName(User.Identity.Name);
                _courseService.AddComment(comment);
            }
            return View("ShowComment", _courseService.GetComments(comment.CourseId));
        }

        public IActionResult ShowComment(int id, int pageId = 1)
        {
            return View(_courseService.GetComments(id, pageId));
        }

        [Authorize]
        public IActionResult CourseVote(int courseId)
        {
            if (!_courseService.IsCourseFree(courseId)
                && !_orderService.IsUserInCourse(User.Identity.Name, courseId)) ViewBag.AccessDenied = true;
            return PartialView(_courseService.GetCourseVotes(courseId));
        }

        [Authorize]
        public IActionResult AddVote(int id, bool vote)
        {
            _courseService.AddVote(_userService.GetUserIdByUserName(User.Identity.Name), id, vote);
            return PartialView("CourseVote", _courseService.GetCourseVotes(id));
        }
    }
}

OnlineCoursePlatform.Web/Controllers/ForumController.cs
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCoursePlatform.Core.Services.Interfaces;
using OnlineCoursePlatform.DataLayer.Entities.Course;
using OnlineCoursePlatform.DataLayer.Entities.Question;
using System.Security.Claims;

namespace OnlineCoursePlatform.Web.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForumService _forumService;
        private readonly IOrderService _orderService;
        public ForumController(IForumService forumService, IOrderService orderService)
        {
            _forumService = forumService;
            _orderService = orderService;

        }

        [Authorize]
        public IActionResult Index(int? courseId, string filter = "", int pageId = 1) 
        {
            ViewBag.CourseId = courseId;
            ViewBag.Filter = filter;
            return View(_forumService.GetQuestions(courseId, filter, pageId));
        } 

        #region Create Question

        [Authorize]
        public IActionResult CreateQuestion(int courseId) => View(new Question()
        {
            CourseId = courseId
        });

        [Authorize]
        [HttpPost]
        public IActionResult CreateQuestion(Question question)
        {
            if (!ModelState.IsValid) return View(question);

            HtmlSanitizer sanitizer = new HtmlSanitizer();
            question.Body = sanitizer.Sanitize(question.Body);

            question.UserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString());
            int questionId = _forumService.AddQuestion(question);
            return RedirectToAction("ShowQuestion", new { questionId = questionId, courseId = question.CourseId});
        }

        #endregion

        #region Show Question

        public IActionResult ShowQuestion(int questionId, int courseId)
        {
            ViewBag.CourseId = courseId;
            return View(_forumService.ShowQuestion(questionId));
        }

        #endregion

        #region Answer

        [Authorize]
        public IActionResult CreateAnswer(int questionId, string body)
        {
            if (!string.IsNullOrEmpty(body))
            {
                HtmlSanitizer sanitizer = new HtmlSanitizer();
                body = sanitizer.Sanitize(body);

                Answer answer = new Answer()
                {
                    AnswerBody = body,
                    QuestionId = questionId,
                    CreateDate = DateTime.Now,
                    UserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString())
                };
                _forumService.AddAnswer(answer);
            } 
            return RedirectToAction("ShowQuestion", new { questionId = questionId,courseId = _forumService.GetQuestionCourseId(questionId)});
        }

        [Authorize]
        public IActionResult UpdateTrueAnswer(int answerId, int questionId)
        {
            int currentUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString());
            Question question = _forumService.ShowQuestion(questionId);

            if(question.UserId == currentUserId 
                || question.Course.TeacherId == currentUserId) _forumService.UpdateAnswerQualification(answerId, questionId);

            return RedirectToAction("ShowQuestion", new { questionId = questionId, courseId = _forumService.GetQuestionCourseId(questionId)});
        }

        #endregion
    }
}

OnlineCoursePlatform.Web/Views/Course/CourseVote.cshtml
@model Tuple<int, int>

@if (User.Identity.IsAuthenticated && ViewBag.AccessDenied == null)
{
    <br />
    <div class="row">
        <h3>
            رای دهی کاربران به دوره :
        </h3>
        <br />
        <p>
            <a class="btn btn-success" onclick="vote(true)">
                <i class="zmdi zmdi-thumb-up"></i>
                می پسندم(@Model.Item1)
            </a>
            <a class="btn btn-danger" onclick="vote(false)">
                <i class="zmdi zmdi-thumb-down"></i>
                نمی پسندم(@Model.Item2)
            </a>
        </p>

    </div>
    <br />
}

OnlineCoursePlatform.Web/Views/Course/Index.cshtml
@model Tuple<List<ShowCourseListItemViewModel>, int>
@{
    ViewData["Title"] = "آرشیو";
}

<div class="container">
    <nav aria-label="breadcrumb">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">پلتفرم دوره های آنلاین</a></li>
        <li class="breadcrumb-item active" aria-current="page">دوره ها</li>
        <li class="breadcrumb-item active" aria-current="page"></li>
      </ul>
    </nav>
</div>

<div class="container">
    <form id="formFilter" action="/Course" method="get">
        <input type="hidden" id="pageid" name="pageId" value="@ViewBag.pageId"/>
        <section class="term-categories">

            <div class="top-bar">

                <header>
                    <h1> دوره های <span> برنامه نویسی وب </span> </h1>
                </header>

                <div class="row">
                    <div class="col-md-4 col-sm-12 col-xs-12 pull-right">
                        <div class="input">
                            <input type="text" name="filter" placeholder="@((ViewBag.filter == null)? "موضوع مورد نظر ...":ViewBag.filter)">                                   
                            <button class="btn btn-success">جستجو</button>
                            <a asp-controller="Course" asp-action="Index" class="btn btn-danger">حذف فیلترها</a>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-12 pull-right">
                        <div class="switch-field available">
                            <input id="available-filter-1" onclick="changeGroup()" name="getType" value="all" @((ViewBag.getType == "all")? "checked":"") type="radio">
                            <label for="available-filter-1"> همه </label>
                            <input id="available-filter-2" onclick="changeGroup()" name="getType" @((ViewBag.getType == "buy")? "checked":"") value="buy" type="radio">
                            <label for="available-filter-2"> خریدنی </label>
                            <input id="available-filter-3" onclick="changeGroup()" name="getType" @((ViewBag.getType == "free")? "checked":"") value="free" type="radio">
                            <label for="available-filter-3"> رایگان </label>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-12 pull-left">
                        <div class="select-ddl">
                            <select name="orederByType">
                                <option value="date"> تاریخ انتشار </option>
                                <option value="updateDate"> تاریخ بروز رسانی </option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">

                <aside class="col-lg-3 col-md-4 col-sm-12 col-xs-12">

                    <section class="aside-section filter-by-price">
                        <header>
                            <h3> فیلتر بر اساس قیمت </h3>
                        </header>
                        <div class="price-range">
                            <input type="hidden" id="min-value" name="startPrice">
                            <input type="hidden" id="max-value" name="endPrice">
                            <div class="price-bar">
                                <div id="priceFilter"></div>
                            </div>
                            <div class="max-price">تا <span id="max-text"></span> تومان</div>
                            <div class="min-price">از <span id="min-text"></span> تومان</div>
                            <div class="clearfix"></div>
                        </div>
                    </section>

                    <section class="aside-section filter-by-category">
                        <header>
                            <h3> دسته بندی موضوعات </h3>
                        </header>
                        <div class="inner">
                            @{
                                List<CourseGroup> groups = ViewBag.Groups as List<CourseGroup>;
                                List<int> selected = ViewBag.selectedGroups as List<int>;
                            }

                            <ul>
                                @foreach (CourseGroup g in groups.Where(g => g.ParentId == null))
                                {
                                    <li>
                                        <input  type="checkbox" onclick="changeGroup()" name="selectedGroups" value="@g.GroupId" @((selected.Any(s=>s==g.GroupId)?"checked":""))/> @g.GroupTitle
                                        <ul>
                                            @if (groups.Any(gr => gr.ParentId == g.GroupId))
                                            {
                                                @foreach(CourseGroup subGroup in groups.Where(gr => gr.ParentId == g.GroupId))
                                                {
                                                    <li>
                                                        <input  type="checkbox" onclick="changeGroup()" name="selectedGroups" value="@subGroup.GroupId" @((selected.Any(s=>s==subGroup.GroupId)?"checked":""))/> @subGroup.GroupTitle
                                                    </li>
                                                }
                                            }
                                        </ul>
                                    </li>
                                }
                            </ul>
                        </div>
                    </section>
                </aside>

                <div class="col-lg-9 col-md-8 col-sm-12 col-xs-12">
                    <section class="terms-items">
                        <div class="row">
                            @foreach(ShowCourseListItemViewModel item in Model.Item1) 
                            {
                                <partial name="_CourseBox" model="item"/>
                            }
                        </div>
                        @if(Model.Item2 > 1)
                        {
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">
                                    @for(int i = 1; i <= Model.Item2; i++)
                                    {
                                        <li class="page-item">
                                            <a class="page-link" onclick="changePage(@i)">@i</a>
                                        </li>
                                    }
                                </ul>
                            </nav>
                        }
                    </section>
                </div>
            </div>
        </section>
    </form>
</div>

@section Scripts{
        <script src="/css/noUiSlider/nouislider.min.js"></script>
        <script src="/js/script.js"></script>
        <script type="text/javascript">

            function changePage(pageid) {
                $("#pageid").val(pageid);
                $("#formFilter").submit();
            }

            $(function () {

                var slider = document.getElementById('priceFilter');
                noUiSlider.create(slider, {
                    start: [0, 500000],
                    step: 5000,
                    connect: true,
                    direction: 'rtl',
                    range: {
                        'min': 0,
                        'max': 500000
                    }
                });

                var marginMin = document.getElementById('min-text'),
                    marginMax = document.getElementById('max-text');

                slider.noUiSlider.on('update', function (values, handle) {
                    var xvalue = Math.round(values[handle]);
                    if (handle) {
                        marginMax.innerHTML = xvalue;
                    } else {
                        marginMin.innerHTML = xvalue;
                    }
                    //console.log(values[handle]);
                });

                slider.noUiSlider.on('change', function (values, handle) {
                    var xvalue = Math.round(values[handle]);
                    if (handle) {
                        // setGetParameter('max_price', xvalue);
                        $('#max-value').val(xvalue);
                    } else {
                        // setGetParameter('min_price', xvalue);
                        $('#min-value').val(xvalue);
                    }
                });

                slider.noUiSlider.on('slide', function (values, handle) {

                    console.log(values[0]);
                    console.log(values[1]);

                    var xvalue = Math.round(values[handle]);
                    //updateSliderRange( Math.round(values[0]), Math.round(values[1]) );
                });

                function updateSliderRange(min, max) {
                    slider.noUiSlider.updateOptions({
                        range: {
                            'min': min,
                            'max': max
                        }
                    });
                }
            });

            function changeGroup() {
                $("#formFilter").submit();
            }
        </script>
}

OnlineCoursePlatform.Web/Views/Course/ShowComment.cshtml
@model Tuple<List<CourseComment>, int>

@{
    Layout = null;
}

@foreach (var item in Model.Item1)
{
    <!-- row -->
    <div class="comment-row">
        <img src="/UserAvatar/@item.User.UserAvatar">
        <div class="left-col">
            <h3> @item.User.UserName </h3>
            <span>@item.CreateDate.ToShamsi()</span>
            <p>
            @item.Comment
                </p>
        </div>
    </div>
    <!-- /row -->
}

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">

       @for (int i = 1; i <= Model.Item2; i++)
       {
           <li class="page-item"><a class="page-link" onclick="pageComment(@i)">@i</a></li>
       }

    </ul>
</nav>

OnlineCoursePlatform.Web/Views/Course/ShowCourse.cshtml
@model Course

@inject IOrderService _OrderService;

@{
    ViewData["Title"] = Model.CourseTitle;

    bool IsUserInCourse = false;

    if (User.Identity.IsAuthenticated)
    {
        IsUserInCourse = _OrderService.IsUserInCourse(User.Identity.Name, Model.CourseId);
    }
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"> پلتفرم دوره های آنلاین </a></li>
            <li class="breadcrumb-item active"><a href="#"> دوره ها </a></li>
            <li class="breadcrumb-item active" aria-current="page"> @Model.CourseTitle </li>
        </ul>
    </nav>
</div>

<div class="container">
    <section class="term-content">
        <header><h1> @Model.CourseTitle </h1></header>
        <div class="row">

            <div class="col-md-8 col-sm-12 col-xs-12 pull-left">
                <section class="term-description">
                    <img src="/course/img/@Model.CourseImageName">

                    @Html.Raw(Model.CourseDescription)

                    @if(!string.IsNullOrEmpty(Model.DemoFileName))
                    {
                        <video style="width:100%" poster="/course/img/@Model.CourseImageName" controls>
                            <source src="/course/demo/@Model.DemoFileName">
                        </video>
                    }

                    <div id="vote">
                        
                    </div>

                    @if (!IsUserInCourse)
                    {
                        <div class="alert alert-info">
                            <p>بعد از ثبت نام در این دوره و تایید فاکتور لینک های دانلود برای شما فعال خواهد شد</p>
                        </div>
                    }

                    <h2> سرفصل های این دوره : </h2>
                    @if(ViewBag.Episode != null)
                    {
                        CourseEpisode episode = ViewBag.Episode as CourseEpisode;

                        <h2>@episode.EpisodeTitle</h2>

                        <video style="width:100%" controls>
                            <source src="@ViewBag.FilePath">
                        </video>
                    }
                    <ul>
                        @foreach (var item in Model.CourseEpisodes)
                        {
                            <li>
                                @if (item.IsFree || IsUserInCourse)
                                {

                                    <h3>
                                        <a href="/DownloadFile/@item.EpisodeId">
                                            @item.EpisodeTitle
                                        </a>
                                    </h3>
                                }
                                else
                                {
                                    <h3>
                                        @item.EpisodeTitle
                                    </h3>
                                }
                                @if (item.IsFree)
                                {
                                    <i> رایگان </i>
                                }
                                else
                                {
                                    <i> نقدی </i>
                                }
                                @if(User.Identity.IsAuthenticated)
                                {
                                    if(item.IsFree || IsUserInCourse)
                                    {
                                        <a href="/ShowCourse/@Model.CourseId?episodeId=@item.EpisodeId">
                                            <i class="zmdi zmdi-play-circle"></i>
                                        </a>
                                    }
                                }
                                <span>@item.EpisodeTime</span>
                            </li>

                        }
                    </ul>
                </section>

                <section class="user-comments">
                    <header><h3> نظرات کاربران </h3></header>
                    <div class="inner">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <form asp-controller="Course" asp-action="CreateComment"
                                  data-ajax="true"
                                  data-ajax-method="post"
                                  data-ajax-mode="replace"
                                  data-ajax-update="#listComment"
                                  data-ajax-success="Success">
                                <input type="hidden" name="comment.CourseId" value="@Model.CourseId" />
                                <div class="row">
                                    <div class="col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <textarea class="form-control" id="comment_Comment" name="comment.Comment" placeholder="متن نظر"></textarea>
                                        </div>

                                    </div>
                                    <div class="col-xs-12">
                                        <button type="submit" class="btn btn-success"> ثبت دیدگاه </button>
                                    </div>
                                </div>
                            </form>
                        }
                        else
                        {
                            <div class="alert alert-danger">
                                جهت درج نظر باید وارد سایت شوید
                            </div>
                        }

                        <div class="comment-list" id="listComment">

                        </div>
                    </div>
                </section>
            </div>

            <aside class="col-md-4 col-sm-12 col-xs-12 pull-right">
                <div class="statistics">
                    <ul>
                        <li>
                            <span> مدت دوره </span>

                            @{
                                TimeSpan time = new TimeSpan(Model.CourseEpisodes.Sum(e => e.EpisodeTime.Ticks));
                            }
                            <i> @time </i>
                        </li>
                        <li>
                            <span> تعداد ویدیوها </span>
                            <i> @Model.CourseEpisodes.Count </i>
                        </li>
                        <li>
                            <span> تعداد دانشجوها </span>
                            <i> @Model.UserCourses.Count نفر </i>
                        </li>
                    </ul>

                    @if (Model.CoursePrice != 0 && !IsUserInCourse)
                    {
                        <a href="/Course/BuyCourse?courseId=@Model.CourseId"> شرکت در دوره : @Model.CoursePrice.ToString("#,0") تومان </a>
                    }
                </div>

                <article class="teacher-info">
                    <img src="/UserAvatar/@Model.User.UserAvatar">
                    <h2> مدرس : @Model.User.UserName </h2>
                </article>

                <article class="term-info">
                    <h2> اطلاعات این دوره </h2>
                    <ul>
                        <li>سطح دوره: @Model.CourseStatus.StatusTitle</li>
                        <li>وضعیت دوره: @Model.CourseLevel.LevelTitle</li>
                        @if (Model.CoursePrice != 0)
                        {
                            <li>قیمت : @Model.CoursePrice.ToString("#,0") تومان</li>
                        }
                        else
                        {
                            <li> قیمت : رایگان </li>
                        }
                        <li>تاریخ ثبت این دوره : @Model.CreateDate.ToShamsi()</li>
                        <li>آخرین بروزرسانی دوره : @Model.UpdateDate?.ToShamsi()</li>
                    </ul>
                </article>

                <div class="share-layer">
                    <span> به اشتراک گذاری </span>
                    <a href="https://github.com/ParsaDdshi"><i class="zmdi zmdi-github"></i></a>
                </div>
                <a class="btn btn-block btn-warning" 
                asp-controller="Forum"
                asp-action="Index"
                asp-route-courseId="@Model.CourseId"> پرسش و پاسخ </a>
                <br />
                @if (Model.Tags != null)
                {
                    <div class="tags-layer">
                        @foreach (string tag in Model.Tags.Split('-', StringSplitOptions.RemoveEmptyEntries))
                        {
                            <a href="/Course?filter=@tag"> @tag </a>
                        }
                    </div>
                }

            </aside>
        </div>
    </section>
</div>

@section Scripts{
    <script src="/js/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        function Success() {
            $("#comment_Comment").val("");
        }

        $(function () {
            $("#listComment").load("/Course/ShowComment/" + @Model.CourseId);
        });

        function pageComment(pageid) {
            $("#listComment").load("/Course/ShowComment/" + @Model.CourseId + "?pageId=" + pageid);
        }

        $(function(){
            $("#vote").load("/Course/CourseVote?courseId=" + @Model.CourseId);
        });

        function vote(vote){
            $("#vote").fadeOut('slow');
            $("#vote").load("/Course/AddVote/@(Model.CourseId)?vote=" + vote);
            $("#vote").fadeIn('slow');
        }
    </script>
}